### ISSUE TITLE
provide user.name and user.email git config settings

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-hub#4]
I wonder if it is somehow magically possible, since users login via github, to pre-populate .gitconfig in "their" account with information from their github account.  That would be really slick.
If not, we at least should populate `~/.gitconfig` with some stub values "DANDI hub users" and "dandiuser@example.com" or alike.  But I really hope that magic is real! ;)

**Comment by satra** [comment]
@choldgraf: any idea if this is possible on jupyterhub?

to populate the home directory when launched with a `.gitconfig` based on github oauth response?

**Comment by choldgraf** [comment]
Mmmm, maybe? It seems like it should be given that you can oauth with GitHub and I believe there are user session spawn hooks that can be configured, but I'm not sure exactly how. I'd ask around on discourse.jupyter.org...

**Comment by satra** [comment]
done: https://discourse.jupyter.org/t/use-github-oauth-to-prepopulate-gitconfig/3041

**Comment by yarikoptic** [comment]
cool,  that [discourse question](https://discourse.jupyter.org/t/use-github-oauth-to-prepopulate-gitconfig/3041/2)  got answers.  @jwodder - could you please look into implementing this for our jupyter hub setup?

**Comment by jwodder** [comment]
Here's what I've been able to figure out so far:

* [This code](https://github.com/jupyterhub/oauthenticator/blob/master/examples/auth_state/jupyterhub_config.py) can be applied to JupyterHub to pass GitHub user details to the "spawner"
* Because we're using Zero to JupyterHub, the proper place to put custom Python configuration code like this is in [`hub.extraConfig` in `config.yaml`](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/advanced.html#hub-extraconfig).
* Even if setting the Git user & email via `git config` isn't feasible, default values for the settings can still be supplied via the `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` environment variables.

To figure out:

* If the code is used to set environment variables, how exactly are those variables passed to Docker?  Are they available at build time or at run time?
* How much of the code is applicable to our instance?  I suspect we might not want to copy the `c.GitHubOAuthenticator.scope = ['gist', 'user:email']` as-is (Should the values be something else?)  Do we need to do anything about `JUPYTERHUB_CRYPT_KEY`, or does Zero to JupyterHub take care of that?

**Comment by satra** [comment]
@jwodder - thank you - i tried it out on one of the instances and overall this works, but would need to figure out if there are some specific things we would want to remove. also it's not setting the email variable.

the place to insert would be here.
https://github.com/dandi/dandihub/blob/dandi/dandi-info/config.yaml.j2#L16

**Comment by yarikoptic** [comment]
@satra - should we establish some "devel" version of the hub so anyone from the team could try to develop changes to it?  I guess we do not want to mess with the main instance until we know the solution which works, right? ;-)

**Comment by satra** [comment]
i don't know about a devel version given some of the specific elements in play. i would be happy to give a full run through of the process (would be good to spread the knowledge).

**Comment by yarikoptic** [comment]
yeah, would be good to have.  Let's setup some quick jitsi for me and @jwodder to attend. My mornings before noon this week are miraculously without anything scheduled.

**Comment by satra** [comment]
done - on the calendar for tomorrow at 11.

**Comment by yarikoptic** [comment]
we derailed a bit into "devel instance".  @jwodder , could you please proceed per [above](https://github.com/dandi/dandi-hub/issues/4#issuecomment-717490867) pointers, or there is any other information is needed? (I have double checked that we still do not populate .gitconfig)

or @satra  HOME is shared across all the hub instances? (thus there would be a race between users changing ~/.gitconfig)

**Comment by satra** [comment]
we only allow one instance per user, so should be ok. i would suggest doing this as part of `config.yaml.j2`.
